ckit/ckit/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
    path("units/", include("units.urls")),
    path("materials/", include("materials.urls")),
    path("projects/", include("projects.urls")),
    path("cities/", include("geo.urls")),
    path("calc_materials/", include("calc_materials.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('fish', TemplateView.as_view(template_name='includes/fish.html'), name='fish')
]

handler404 = "core.views.page_not_found"  # noqa
handler500 = "core.views.server_error"  # noqa

ckit/geo/urls.py
from django.urls import path

from .views import CityCreateView, CityDeleteView, CityListView

app_name = "geo"

urlpatterns = [
    path("", CityListView.as_view(), name="list"),
    path("new/", CityCreateView.as_view(), name="new"),
    path("rm/<int:pk>/", CityDeleteView.as_view(), name="remove"),
]

ckit/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("profile/", views.profile, name="profile"),
]

ckit/templates/includes/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" rel="stylesheet">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css">
    <script src="https://kit.fontawesome.com/a3b4d66411.js" crossorigin="anonymous"></script>
    {% block load_scripts%}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <style>
      .brd {
          border: 1px solid red;
      }
      .scroll {
          height:400px;
          overflow-y: scroll;
        }
      .select {
          height: 250px;
      }
  </style>
  </head>
  <body>
    {% csrf_token %}
    <div id="panel" class="container text-left">
      
      <header>
        <div class="row">
          <div class="col">
            {% include 'includes/nav.html' %}
          </div>
        </div>
      </header>
      <main>
        <div class="row">
          {% block content %}
          {% endblock %}
        </div>
      </main>
      
      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        {% include 'includes/footer.html' %} 
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html> 

ckit/templates/includes/fish.html
{% extends 'includes/base.html' %}
{% block content %}
<style>
    .brd {
        border: 1px solid black;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col text-center brd">
            bread / crubms / home
        </div>
    </div>
    <div class="row">
        <div class="col-1 brd">
            21
        </div>
        <div class="col-5 brd">
            22
        </div>
        <div class="col-1 brd">
            23
        </div>
        <div class="col-5 brd">
            24
        </div>
    </div>
    <div class="row">
        <div class="col text-center brd">
            bottom
        </div>
    </div>
</div>
{% endblock%}

ckit/templates/includes/footer.html
<p class="m-0 text-dark text-center ">Sumenko V. | <span style="color:red">C</span>onstructorKit © {% now "Y" %}, все права защищены.</p>

ckit/templates/includes/login_required.html
Пользоваться могут зарегистрированные пользователи. <a href="{% url 'login' %}">Войти</a>

ckit/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="/"><span style="color:red">C</span>onstructor Kit</a>
        <nav>
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}">
                    <b>
                        <span style="color:red">
                            {{ user.username.0|upper }}
                        </span>
                        <span style="color:rgb(0, 0, 0)">
                            {{ user.username|slice:"1:" }}
                        </span>.
                    </b>
                </a>
                {% if user.is_staff %}
                <a href='/admin/'>#</a>
                <a href="{% url 'fish' %}"><i class="fa fa-fish"></i></a>
                {% endif %}
                <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
                <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>

            {% else %}
                <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
                <a class="p-2 text-dark" href="{% url 'users:signup' %}">Регистрация</a>
            {% endif %}
        </nav>
</nav>