ckit/ckit/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
    path("units/", include("units.urls")),
    path("materials/", include("materials.urls")),
    path("projects/", include("projects.urls")),
    path("cities/", include("geo.urls")),
    path("calc_materials/", include("calc_materials.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('fish', TemplateView.as_view(template_name='includes/fish.html'), name='fish')
]

handler404 = "core.views.page_not_found"  # noqa
handler500 = "core.views.server_error"  # noqa

ckit/geo/urls.py
from django.urls import path

from .views import CityCreateView, CityDeleteView, CityListView

app_name = "geo"

urlpatterns = [
    path("", CityListView.as_view(), name="list"),
    path("new/", CityCreateView.as_view(), name="new"),
    path("rm/<int:pk>/", CityDeleteView.as_view(), name="remove"),
]

ckit/geo/models.py
from django.db import models
from roman import fromRoman, toRoman


class City(models.Model):
    name = models.CharField(
        verbose_name="Название", max_length=30, blank=False, unique=True
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "Город"
        verbose_name_plural = "Города"

    def __str__(self):
        return self.name
    
    @property
    def get_name(self):
        if self.name:
              return self.name
        else:
              return "<!>"

class StandartName(models.Model):
    name = models.CharField(
        max_length=50, verbose_name="Название", blank=False, unique=True
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "Нормативный документ"
        verbose_name_plural = "Нормативный документы"

    def __str__(self):
        return self.name


class RegionSnow(models.Model):
    SNOW_REGION_CHOICES = [(i, toRoman(i)) for i in range(1, 8 + 1)]
    standart = models.ForeignKey(
        StandartName, on_delete=models.CASCADE, blank=False
    )
    region_snow = models.SmallIntegerField(
        verbose_name="Снеговой район",
        choices=SNOW_REGION_CHOICES,
        default="I",
        blank=False,
    )

    class Meta:
        verbose_name = "Снеговой район"
        verbose_name_plural = "Снеговые районы"
        unique_together = [["standart", "region_snow"]]

    def __str__(self):
        return toRoman(self.region_snow)


class RegionWind(models.Model):
    WIND_REGION_CHOICES = [(i, toRoman(i)) for i in range(1, 7 + 1)]
    standart = models.ForeignKey(
        StandartName, on_delete=models.CASCADE, blank=False
    )
    region_wind = models.SmallIntegerField(
        verbose_name="Ветровой район",
        choices=WIND_REGION_CHOICES,
        default="I",
        blank=False,
    )

    class Meta:
        verbose_name = "Ветровой район"
        verbose_name_plural = "Ветровые районы"
        unique_together = [["standart", "region_wind"]]

    def __str__(self):
        return toRoman(self.region_wind)


class CityData(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, blank=False)
    standart = models.ForeignKey(
        StandartName, on_delete=models.CASCADE, blank=False
    )
    snow = models.ForeignKey(RegionSnow, on_delete=models.CASCADE, blank=False)
    wind = models.ForeignKey(RegionWind, on_delete=models.CASCADE, blank=False)

    class Meta:
        verbose_name = "Данные города"
        verbose_name_plural = "Данные городов"
        unique_together = [["city", "standart"]]

ckit/geo/forms.py
from django import forms

from .models import City


class CityForm(forms.ModelForm):
    class Meta:
        model = City

        fields = ("name",)
        widgets = {"name": forms.TextInput(attrs={"autofocus": "autofocus"})}

ckit/geo/views.py
from typing import Any, Dict

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView

from .forms import CityForm
from .models import City


class CityCreateView(LoginRequiredMixin, CreateView):
    model = City
    form_class = CityForm
    success_url = reverse_lazy("geo:list")
    login_url = reverse_lazy("login")


class CityListView(TemplateView):
    template_name = "geo/cities.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["table"] = {
            "counter": True,
            "heads": ("Город", "#action"),
            "lines": [
                {
                    "data": [city],
                    "link": f"link_to { city.pk }",
                    "delete_link": reverse_lazy(
                        "geo:remove", kwargs={"pk": city.pk}
                    ),
                }
                for city in City.objects.all()
            ],
        }
        return context


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    success_url = reverse_lazy("geo:view")

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["back_url"] = reverse_lazy("geo:view")
        return context

ckit/geo/templates/geo/cities.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
                <a href={% url 'index' %}><i class="fa-solid fa-house"></i></a> / <i class="fa-solid fa-map-location-dot"></i> Города
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include 'includes/widgets/table.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <div class="btn-group">    
                {% if user.is_staff %}
                <a class="btn btn-primary" href="{% url 'geo:new' %}">Создать</a>
                {% endif %}
                <a class="btn btn-primary" href="..">Назад</a>
                {% endblock %}
            </div>
        </div>
    </div>
</div>

ckit/geo/templates/geo/city_confirm_delete.html
{% extends 'includes/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Удалить "{{ object }}"?</p>
    {{ form }}
    <input type="submit" class="btn btn-danger" value="Удалить">
    <a class="btn btn-primary" href="{{ back_url }}">Назад</a>
</form>  
{% endblock %}

ckit/geo/templates/geo/city_form.html
{% extends 'includes/base.html' %}
{% block content %}

<form method="post" action="{% url 'geo:new' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Создать">
    <a class="btn btn-primary" href="..">Назад</a>
  </form>
  
{% endblock %}