ckit/calc_materials/urls.py
from django.urls import path

from .views import (
    add_to_tree, delete_from_tree, short_tree, get_update_node, get_tree
)

app_name = "calc_materials"

urlpatterns = [
    path("<int:pk>/", short_tree, name="list"),
    path("<int:pk>/add/<int:node>/<int:pk_element>/", add_to_tree, name="add"),
    path("<int:pk>/rm/<int:node>/", delete_from_tree, name="remove"),
    path("<int:pk>/node/<int:node_pk>/", get_update_node, name="edit_node"),
    path("<int:pk>/g/", get_tree, name="edit_node"),
]

ckit/ckit/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
    path("units/", include("units.urls")),
    path("materials/", include("materials.urls")),
    path("projects/", include("projects.urls")),
    path("cities/", include("geo.urls")),
    path("calc_materials/", include("calc_materials.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('fish', TemplateView.as_view(template_name='includes/fish.html'), name='fish')
]

handler404 = "core.views.page_not_found"  # noqa
handler500 = "core.views.server_error"  # noqa

ckit/geo/urls.py
from django.urls import path

from .views import CityCreateView, CityDeleteView, CityListView

app_name = "geo"

urlpatterns = [
    path("", CityListView.as_view(), name="list"),
    path("new/", CityCreateView.as_view(), name="new"),
    path("rm/<int:pk>/", CityDeleteView.as_view(), name="remove"),
]

ckit/projects/urls.py
from django.urls import path

from .views import (
    ProjectCalculatorsView, ProjectDeleteView, ProjectsListView,
    add_create_material_to_project, add_update_material_to_project,
    new_update_project, project_view_materials, remove_material_from_project,
)

app_name = 'projects'

urlpatterns = [
    path('', ProjectsListView.as_view(), name='list'),
    path('new/', new_update_project, name='new'),
    path('edit/<int:pk>/', new_update_project, name='edit'),
    path('<int:pk>/', ProjectCalculatorsView.as_view(), name='detail'),
    path('<int:pk>/materials/', project_view_materials, name='project_materials'),
    path('<int:pk>/add/', add_update_material_to_project,
         name='add_to_project'),
    path('<int:pk>/add_create/', add_create_material_to_project,
         name='add_create_to_project'),
    path('<int:pk>/edit/<int:material_pk>/', add_update_material_to_project,
                                             name='mat-detail'),
    path(
        '<int:pk>/rm/<int:material_pk>',
        remove_material_from_project,
        name='remove_material',
    ),
    path('rm/<int:pk>/', ProjectDeleteView.as_view(), name='remove'),
]

ckit/projects/models.py
from django.contrib.auth import get_user_model
from django.db import models
from geo.models import City
from templates.messages import messages

User = get_user_model()


class Project(models.Model):
    name = models.CharField(
        max_length=50, blank=False, verbose_name="Название проекта"
    )

    city = models.ForeignKey(City, null=True, blank=True,
                             verbose_name='Местоположение',
                             on_delete=models.DO_NOTHING)
    
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="projects",
        verbose_name="Владелец",
    )

    def __str__(self):
        return self.name


    class Meta:
        unique_together = [["name", "owner"]]
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"

    # city
    # address
    # buildings
    # properties

ckit/projects/forms.py
from calc_materials.models import ProjectTree
from django.core.exceptions import NON_FIELD_ERRORS
from django.db import transaction
from django.forms import CharField, HiddenInput, ModelForm, TextInput
from materials.models import Material, Project, ProjectHasMaterial
from templates.messages import messages

from .models import Project


class AddMaterialToProjectForm(ModelForm):
    
    class Meta:
        model = ProjectHasMaterial
        fields = ['material', 'level', 'project', 'add_to_report']
        widgets = {'project': HiddenInput()}


class AddProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'owner': HiddenInput(),
            'name': TextInput(attrs={'autofocus': 'autofocus'}),
        }

        error_messages = {
            NON_FIELD_ERRORS: {'unique_together': f'Уже существует'}
        }


    @transaction.atomic
    def save(self, commit=True):
        instance = super(AddProjectForm, self).save(commit=False)
        if commit:
            instance.save()
            entry_material = Material.objects.get(name='/')
            entry = ProjectHasMaterial.objects.create(
                project=instance,
                material=entry_material,
                add_to_report=False,
                level=ProjectHasMaterial.Levels.ROOT
            )
            ProjectTree.objects.create(parent=None, element=entry, qty=1)
        return instance

ckit/projects/views.py
from django.template.loader import render_to_string
from typing import Any, Dict
from django.db.models import Q


from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView
from materials.models import ProjectHasMaterial, Material

from .forms import AddMaterialToProjectForm, AddProjectForm
from .models import Project
from materials.models import ProjectHasMaterial
from calc_materials.models import ProjectTree


User = get_user_model()


class ProjectsListView(LoginRequiredMixin, TemplateView):
    template_name = 'projects/view_project_list.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        projects = Project.objects.filter(owner=self.request.user)
        context['projects'] = projects
        context['table'] = {
            'counter': True,
            'heads': ('id', 'Проект', 'Место', '#action'),
            'lines': [
                {
                    'data': [project.pk, project.name,
                             project.city],
                    'link': reverse_lazy('projects:detail',
                                         kwargs={'pk': project.pk}),
                    'delete_link': reverse_lazy(
                       'projects:remove', kwargs={'pk': project.pk}
                    ),
                    'edit_link': reverse_lazy('projects:edit',
                                              kwargs={'pk': project.pk})
                }
                for project in projects
            ],
        }
        
        return context


@login_required
def new_update_project(request, pk=None):
    instance = None
    commit = True
    if pk:
        instance = get_object_or_404(Project, pk=pk, owner=request.user)
    else:
        instance = Project(owner=request.user)
    
    form = AddProjectForm(request.POST or None, instance=instance)
    if request.GET or not form.is_valid():
        return render(request, 'projects/project_form.html',
                      context={'form': form, 'pk': pk,
                               'back_url': reverse_lazy('projects:list')})
    
    if pk: # if update
        commit=False
    a = form.save(commit=commit)
    a.save()
    return redirect('projects:list')


class ProjectNewView(LoginRequiredMixin, CreateView):
    form_class = AddProjectForm
    template_name = 'projects/project_form.html'
    success_url = reverse_lazy('projects:list')
    login_url = reverse_lazy('login')

    def get_form_kwargs(self) -> Dict[str, Any]:
        # Put user to kw for form class
        kwargs = super(ProjectNewView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class ProjectCalculatorsView(LoginRequiredMixin, TemplateView):
    template_name = 'projects/view_project_detail.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['calculators'] = [
            {
                'name': 'Подсчет материалов',
                'link': 'calc_materials:list'},
            {
                'name': 'Библиотека материалов',
                'link': 'projects:project_materials',
            },
            {'name': 'Расчет кровли', 'link': ''},
            {'name': 'Расчет балок и стропил', 'link': ''},
        ]
        pk = kwargs['pk']
        context['pk'] = pk
        context['title'] = get_object_or_404(Project, pk=pk).name
        return context


@login_required
def add_update_material_to_project(request, pk, material_pk=None):
    """ Add material to project library """
    project = Project.objects.get(pk=pk)
    if request.user != project.owner:
        return redirect('projects:project_materials', pk)
    update = False
    material = None
    if material_pk:
        material = Material.objects.get(pk=material_pk)
        instance = ProjectHasMaterial.objects.get(project=project,
                                                  material=material)
    else:
        instance = ProjectHasMaterial(project=project, add_to_report=True)

    form = AddMaterialToProjectForm(request.POST or None, instance=instance)

    if request.GET or not form.is_valid():
        if material:
            update = True
        
        return render(
            request,
            'projects/add_material_form.html',
            context={'form': form, 'project': project, 'material': material,
                     'update': update},
        )

    form.save()

    return redirect('projects:project_materials', pk)

@login_required
def remove_material_from_project(request, pk, material_pk):
    record = ProjectHasMaterial.objects.get(project=pk, material=material_pk)
    if record.project.owner == request.user:
        record.delete()
    return redirect('projects:project_materials', pk)

class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects:list')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['back_url'] = reverse_lazy('projects:list')
        return context
    
    def form_valid(self, request):
        self.object = self.get_object()
        # user = User.objects.get(username=self.request.user)
        if self.request.user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        return render(self.request, 'materials/material_delete_forbidden.html',
                      context={'back_url': self.get_success_url()})


def add_create_material_to_project(request, pk):
    return HttpResponse(f'add_create_material_to_project for {pk}')
    # user = User.objects.get(username=request.user)
    # project = Project.objects.get(owner=user, pk=pk)
    # formset = formset_factory(AddMaterialForm, extra=2)
    # form_create_material = AddMaterialToProjectForm()
    # form_create_material.project = project
    # return render(request, 'projects/add_create_material_form.html',
    #               context={'form_create_material': formset, 
    #                        'form_add_material': form_create_material})


@login_required
def project_view_materials(request, pk):
    project = get_object_or_404(Project, pk=pk)
    param = request.GET.get('q')

    table = None
    obj = ProjectHasMaterial.objects.filter(project=project).filter(Q(project__owner=request.user) | Q(project__owner__is_staff=True))
    if param and request.user == project.owner:        
        obj = obj.filter(material__name__icontains=param)
    obj = obj.order_by('level', 'material__name')

    table = {
        'heads': ('Наименование', 'Уровень', 'Ед.изм.', '#action'),
        'lines': [
            {'data': (a.material.name, a.level, a.material.units),

             'link': '',
             'delete_link': reverse_lazy(
                  'projects:remove_material', kwargs={'pk': pk,
                                                      'material_pk': a.material.pk}
                    ),
             'edit_link': reverse_lazy('projects:mat-detail',
                                       kwargs={'pk': pk,
                                       'material_pk': a.material.pk}),}
            for a in obj
        ]
    }
    does_req_accept_json = request.accepts("application/json")
    is_ajax_request = request.headers.get('x-requested-with') == "XMLHttpRequest" and does_req_accept_json
    
    if is_ajax_request:

        html = render_to_string(
            template_name='includes/widgets/table.html',
            context={'table': table}
        )
        data_dict = {'html_from_view': html}
        return JsonResponse(data=data_dict, safe=False)

    context = {}
    context['table'] = table
    context['title'] = project.name
    context['pk'] = pk
    context['action_name'] = 'Добавить'
    context['action_url'] = reverse_lazy('projects:add_to_project',
                                            kwargs={'pk': pk})
    context['back_url'] = reverse_lazy('projects:detail',
                                           kwargs={'pk': pk})
    if param: context['back_url'] += '/?q' + param
    
    return render(request, 'projects/view_project_materials.html', context=context)

ckit/projects/templates/projects/add_create_material_form.html
{% extends 'includes/base.html' %}
{% block content %}
<p>{{ project.name }}</p>
<p>{% if update %} Редактировать{% else %}Добавить{% endif %} элемент</p>
<form method="post">
    {% csrf_token %}
    {{ form_create_material.as_p }}
    {{ form_add_material.as_p }}
    <input type="submit" class="btn btn-primary" value="{% if update %} Сохранить {% else %}Добавить{% endif %}">
    <a class="btn btn-primary" href="{% url 'projects:project_materials' project.id %}">Назад</a>
  </form> 
{% endblock %}

ckit/projects/templates/projects/add_material_form.html
{% extends 'includes/base.html' %}
{% block content %}
<p>{{ project.name }}</p>
<p>{% if update %} Редактировать{% else %}Добавить{% endif %} элемент</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="{% if update %} Сохранить {% else %}Добавить{% endif %}">
    <a class="btn btn-primary" href="{% url 'projects:project_materials' project.id %}">Назад</a>
  </form> 
{% endblock %}

ckit/projects/templates/projects/project_confirm_delete.html
{% extends 'includes/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Удалить "{{ object }}"?</p>
    {{ form }}
    <input type="submit" class="btn btn-danger" value="Удалить">
    <a class="btn btn-primary" href="{{ back_url }}">Назад</a>
</form>  
{% endblock %}

ckit/projects/templates/projects/project_form.html
{% extends 'includes/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Создать">
    <a class="btn btn-primary" href="{{ back_url }}">Назад</a>
 </form> 
{% endblock %}

ckit/projects/templates/projects/view_project_detail.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <a href={% url 'index' %}><i class="fa-solid fa-house"></i></a> / <a href={% url 'projects:list' %}> Проекты </a> / {{ title }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-hover">
                <tbody>
                    {% for calculator in calculators %}
                    {% if calculator.link == '' %}
                    <tr  class="clickable-row" data-href="">
                        <td><span class="link-secondary">{{ calculator.name }}</span></td>
                        {% else %}
                    <tr  class="clickable-row" data-href="{% url calculator.link pk %}">
                        <td>{{ calculator.name }}</td>
                    {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
    });
</script>
{% endblock %}

ckit/projects/templates/projects/view_project_list.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <a href={% url 'index' %}><i class="fa-solid fa-house"></i></a> / Проекты
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include 'includes/widgets/table.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <div class="btn-group">
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'projects:new' %}">Создать</a>
                {% else %}
                <button role="button" class="btn btn-secondary"  data-toggle="tooltip" data-placement="bottom" title="Нужно залогиниться">Создать</button>
                {% endif %}
                <a class="btn btn-primary" href="..">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ckit/projects/templates/projects/view_project_materials.html
{% extends 'includes/base.html' %}
{% block content %}
<script>
    const endpoint = '/projects/{{ pk }}/materials/'
</script>

<div class="container">
    <div class="row">
        <div class="col">
                <a href={% url 'index' %}><i class="fa-solid fa-house"></i></a> / <a href={% url 'projects:list' %}> Проекты </a> / <a href={% url 'projects:detail' pk %}>{{ title }}</a> / Материалы
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include 'includes/widgets/search_panel.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <div class="btn-group">
                {% include 'includes/widgets/action_back_buttons.html' %}
                <a class="btn btn-info" href="#">Создать</a>
                <button class="btn btn-success" href="#" onclick="window.location='{% url 'calc_materials:list' pk %}'"><i class="fa-solid fa-tree"></i>&nbspПодсчет материалов</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}